export interface FormulaDefinition {
  id: string;
  name: string;
  category: 'Financial' | 'Customer Economics' | 'Forecasting' | 'Attribution';
  equation: string;
  variables: { name: string; symbol: string; unit: string; description: string }[];
  explanation: string;
  cimLearningOutcome: string;
  calculate: (inputs: Record<string, number>) => { result: number; unit: string; steps: string[] };
}

export const CIM_FORMULAS: FormulaDefinition[] = [
  {
    id: 'romi',
    name: 'Return on Marketing Investment (ROMI)',
    category: 'Financial',
    equation: 'ROMI = [ ( (Gross Revenue × Gross Margin %) - Marketing Cost ) / Marketing Cost ] × 100%',
    variables: [
      { name: 'Gross Revenue', symbol: 'R', unit: '£', description: 'Total revenue generated from marketing campaign' },
      { name: 'Gross Margin', symbol: 'M', unit: '%', description: 'Product or service gross margin percentage' },
      { name: 'Marketing Spend', symbol: 'C', unit: '£', description: 'Total direct marketing campaign expenditure' }
    ],
    explanation: 'Measures the net financial efficiency and profit contribution directly generated by marketing expenditure. A positive ROMI indicates value creation beyond initial capital outlay.',
    cimLearningOutcome: 'LO 1.1 (Financial Metrics: ROMI/ROI, Margin, Profit)',
    calculate: (inputs) => {
      const R = inputs['R'] || 0;
      const M = (inputs['M'] || 100) / 100;
      const C = inputs['C'] || 1;
      const grossProfit = R * M;
      const netProfit = grossProfit - C;
      const romi = (netProfit / C) * 100;
      return {
        result: Math.round(romi * 100) / 100,
        unit: '%',
        steps: [
          `Gross Profit = Gross Revenue (£${R.toLocaleString()}) × Margin (${(M * 100)}%) = £${grossProfit.toLocaleString()}`,
          `Net Marketing Profit = Gross Profit (£${grossProfit.toLocaleString()}) - Marketing Spend (£${C.toLocaleString()}) = £${netProfit.toLocaleString()}`,
          `ROMI = (£${netProfit.toLocaleString()} / £${C.toLocaleString()}) × 100% = ${romi.toFixed(2)}%`
        ]
      };
    }
  },
  {
    id: 'cac',
    name: 'Customer Acquisition Cost (CAC)',
    category: 'Customer Economics',
    equation: 'CAC = Total Marketing & Sales Spend / Total New Customers Acquired',
    variables: [
      { name: 'Marketing & Sales Spend', symbol: 'S', unit: '£', description: 'Total acquisition spend in the period' },
      { name: 'New Customers', symbol: 'N', unit: 'Count', description: 'Total number of newly acquired paying customers' }
    ],
    explanation: 'Represents the average total cost incurred to acquire a single new paying customer. Must be analyzed alongside Customer Lifetime Value (CLV).',
    cimLearningOutcome: 'LO 1.1 & LO 2.1 (Customer Acquisition Cost & Efficiency)',
    calculate: (inputs) => {
      const S = inputs['S'] || 0;
      const N = inputs['N'] || 1;
      const cac = S / N;
      return {
        result: Math.round(cac * 100) / 100,
        unit: '£ / customer',
        steps: [
          `Total Spend = £${S.toLocaleString()}`,
          `New Customers Acquired = ${N.toLocaleString()}`,
          `CAC = £${S.toLocaleString()} / ${N.toLocaleString()} = £${cac.toFixed(2)}`
        ]
      };
    }
  },
  {
    id: 'clv',
    name: 'Customer Lifetime Value (CLV / LTV)',
    category: 'Customer Economics',
    equation: 'CLV = (Average Revenue per Customer × Gross Margin %) / Churn Rate %',
    variables: [
      { name: 'Average Revenue per Customer', symbol: 'ARPU', unit: '£/yr', description: 'Annual or monthly average revenue per customer' },
      { name: 'Gross Margin %', symbol: 'M', unit: '%', description: 'Gross profit margin percentage' },
      { name: 'Churn (Attrition) Rate %', symbol: 'Ch', unit: '%', description: 'Periodic customer cancellation/attrition rate' }
    ],
    explanation: 'Projects the cumulative gross profit expected from a single customer relationship over their entire tenure. Benchmark healthy ratio is CLV:CAC >= 3:1.',
    cimLearningOutcome: 'LO 1.1 & LO 2.1 (CLV, Attrition rate, LTV:CAC Ratio)',
    calculate: (inputs) => {
      const arpu = inputs['ARPU'] || 0;
      const m = (inputs['M'] || 100) / 100;
      const ch = (inputs['Ch'] || 10) / 100;
      const avgLifespan = 1 / ch;
      const clv = (arpu * m) / ch;
      return {
        result: Math.round(clv * 100) / 100,
        unit: '£',
        steps: [
          `Average Customer Lifespan = 1 / Churn (${(ch * 100).toFixed(1)}%) = ${avgLifespan.toFixed(1)} periods`,
          `Periodic Gross Margin per Customer = £${arpu.toLocaleString()} × ${(m * 100)}% = £${(arpu * m).toFixed(2)}`,
          `CLV = £${(arpu * m).toFixed(2)} × ${avgLifespan.toFixed(1)} = £${clv.toFixed(2)}`
        ]
      };
    }
  },
  {
    id: 'breakeven',
    name: 'Break-Even Volume (Units & Revenue)',
    category: 'Financial',
    equation: 'Break-Even Units = Fixed Marketing Overheads / (Selling Price - Variable Cost per Unit)',
    variables: [
      { name: 'Fixed Marketing Overheads', symbol: 'F', unit: '£', description: 'Total fixed costs of the campaign' },
      { name: 'Selling Price per Unit', symbol: 'P', unit: '£', description: 'Unit selling price' },
      { name: 'Variable Cost per Unit', symbol: 'V', unit: '£', description: 'Direct unit cost of production/delivery' }
    ],
    explanation: 'Identifies the precise operational volume required to cover fixed marketing costs before generating profit (Contribution = Fixed Costs).',
    cimLearningOutcome: 'LO 1.1 (Break-even point & Cost/Volume/Profit analysis)',
    calculate: (inputs) => {
      const F = inputs['F'] || 0;
      const P = inputs['P'] || 1;
      const V = inputs['V'] || 0;
      const unitContribution = P - V;
      const beUnits = unitContribution > 0 ? F / unitContribution : 0;
      const beRevenue = beUnits * P;
      return {
        result: Math.ceil(beUnits),
        unit: 'Units',
        steps: [
          `Unit Contribution Margin = Price (£${P}) - Variable Cost (£${V}) = £${unitContribution.toFixed(2)}`,
          `Break-Even Volume = £${F.toLocaleString()} / £${unitContribution.toFixed(2)} = ${Math.ceil(beUnits).toLocaleString()} units`,
          `Break-Even Revenue = ${Math.ceil(beUnits).toLocaleString()} units × £${P} = £${Math.round(beRevenue).toLocaleString()}`
        ]
      };
    }
  },
  {
    id: 'variance',
    name: 'Marketing Budget Variance Analysis',
    category: 'Forecasting',
    equation: 'Variance = Budgeted Amount - Actual Amount (Favorable if Actual Spend < Budget or Actual Revenue > Budget)',
    variables: [
      { name: 'Budgeted Spend', symbol: 'B', unit: '£', description: 'Planned budget allowance' },
      { name: 'Actual Spend', symbol: 'A', unit: '£', description: 'Actual recorded expenditure' }
    ],
    explanation: 'Distinguishes between favorable and adverse variances to assess operational discipline, efficiency improvements, or unexpected cost escalations.',
    cimLearningOutcome: 'LO 3.2 (Budget management through variance analysis)',
    calculate: (inputs) => {
      const B = inputs['B'] || 0;
      const A = inputs['A'] || 0;
      const diff = B - A;
      const isFavorable = diff >= 0;
      return {
        result: Math.abs(diff),
        unit: isFavorable ? '£ (Favorable)' : '£ (Adverse)',
        steps: [
          `Budgeted = £${B.toLocaleString()}`,
          `Actual Spend = £${A.toLocaleString()}`,
          `Variance = £${Math.abs(diff).toLocaleString()} (${isFavorable ? 'FAVORABLE - Under Budget' : 'ADVERSE - Over Budget'})`,
          `Percentage Variance = ${(((A - B) / (B || 1)) * 100).toFixed(2)}%`
        ]
      };
    }
  }
];
