import { ExamQuestion } from '../../types/cim';

export const COMMERCIAL_INTELLIGENCE_EXAM_QUESTIONS: ExamQuestion[] = [
  // --- LO1: Financial & Marketing Performance Metrics (Questions 1 to 15) ---
  {
    id: 1,
    loId: 'LO1',
    criterionId: '1.1',
    commandVerb: 'Determine',
    isNumerical: true,
    difficulty: 'intermediate',
    scenario: 'A B2B marketing team invested £80,000 in an omnichannel campaign during Q1. The campaign generated £320,000 in gross revenue with a gross profit margin of 40%.',
    question: 'Determine the Return on Marketing Investment (ROMI) for this campaign.',
    options: [
      { id: 'A', text: '60%' },
      { id: 'B', text: '160%' },
      { id: 'C', text: '300%' },
      { id: 'D', text: '400%' }
    ],
    correctAnswer: 'A',
    explanation: {
      rationale: 'ROMI is calculated as: [(Gross Profit Generated by Marketing - Marketing Investment) / Marketing Investment] × 100%. Gross profit = £320,000 × 40% = £128,000. Net marketing profit = £128,000 - £80,000 = £48,000. ROMI = (£48,000 / £80,000) × 100% = 60%.',
      calculationSteps: [
        'Gross Revenue = £320,000',
        'Gross Margin = 40% -> Gross Profit = £320,000 × 0.40 = £128,000',
        'Marketing Investment = £80,000',
        'Net Incremental Margin = £128,000 - £80,000 = £48,000',
        'ROMI = (£48,000 / £80,000) × 100% = 60.0%'
      ],
      distractorAnalysis: {
        'B': 'Calculates gross profit divided by investment (£128k/£80k = 160%) without subtracting initial marketing expenditure.',
        'C': 'Calculates net revenue over cost ((£320k-£80k)/£80k = 300%) ignoring the 40% gross profit margin.',
        'D': 'Calculates total revenue divided by investment (£320k/£80k = 400%), confusing revenue multiple with ROMI.'
      },
      syllabusReference: 'CIM Commercial Intelligence Specification LO 1.1 (Financial Metrics: ROMI/ROI, Margin)'
    }
  },
  {
    id: 2,
    loId: 'LO1',
    criterionId: '1.1',
    commandVerb: 'Determine',
    isNumerical: true,
    difficulty: 'intermediate',
    scenario: 'An e-commerce retailer spent £45,000 on digital acquisition across 3 months. The campaign produced 1,500 new buying customers with an average order value of £60 and an average gross margin of 50%.',
    question: 'Determine the Customer Acquisition Cost (CAC) and the initial gross profit contribution per acquired customer.',
    options: [
      { id: 'A', text: 'CAC is £30.00; Initial gross profit contribution is £30.00' },
      { id: 'B', text: 'CAC is £45.00; Initial gross profit contribution is £60.00' },
      { id: 'C', text: 'CAC is £30.00; Initial gross profit contribution is £60.00' },
      { id: 'D', text: 'CAC is £15.00; Initial gross profit contribution is £30.00' }
    ],
    correctAnswer: 'A',
    explanation: {
      rationale: 'CAC = Total Marketing Spend / Number of Acquired Customers = £45,000 / 1,500 = £30.00. Initial gross profit contribution = Average Order Value × Gross Margin = £60 × 50% = £30.00. (The initial transaction breaks even on acquisition spend).',
      calculationSteps: [
        'CAC = £45,000 / 1,500 = £30.00',
        'Gross Profit per Order = £60.00 × 0.50 = £30.00'
      ],
      distractorAnalysis: {
        'B': 'Incorrectly assumes CAC is £45 and confuses revenue with profit contribution.',
        'C': 'Correctly calculates CAC but uses gross revenue rather than gross profit contribution.',
        'D': 'Mistakes gross margin percentage calculation for spend.'
      },
      syllabusReference: 'CIM Commercial Intelligence Specification LO 1.1 (Customer Acquisition Cost & Marketing Contribution)'
    }
  },
  {
    id: 3,
    loId: 'LO1',
    criterionId: '1.1',
    commandVerb: 'Determine',
    isNumerical: true,
    difficulty: 'advanced',
    scenario: 'A subscription software firm charges £50/month per user with an 80% gross margin. The average monthly customer churn (attrition) rate is 4%.',
    question: 'Determine the expected Customer Lifetime Value (CLV / LTV) for a newly acquired customer.',
    options: [
      { id: 'A', text: '£1,000' },
      { id: 'B', text: '£1,250' },
      { id: 'C', text: '£800' },
      { id: 'D', text: '£1,500' }
    ],
    correctAnswer: 'A',
    explanation: {
      rationale: 'Average Customer Lifetime (months) = 1 / Churn Rate = 1 / 0.04 = 25 months. Monthly Gross Margin per customer = £50 × 80% = £40. CLV = Monthly Gross Profit × Average Customer Lifetime = £40 × 25 months = £1,000.',
      calculationSteps: [
        'Average Customer Lifespan = 1 / 0.04 = 25 months',
        'Monthly Gross Margin = £50 × 80% = £40',
        'CLV = £40 × 25 = £1,000'
      ],
      distractorAnalysis: {
        'B': 'Calculates CLV using total subscription revenue (£50 × 25 = £1,250) without applying the 80% margin.',
        'C': 'Multiplies £40 by 20 months instead of the true inverse churn lifespan of 25 months.',
        'D': 'Uses an incorrect annualized multiplier.'
      },
      syllabusReference: 'CIM Commercial Intelligence Specification LO 1.1 (Customer Lifetime Value & Attrition Rate)'
    }
  },
  {
    id: 4,
    loId: 'LO1',
    criterionId: '1.1',
    commandVerb: 'Analyse',
    isNumerical: true,
    difficulty: 'intermediate',
    scenario: 'A marketing manager plans a product launch campaign with £60,000 in fixed marketing overheads. The product sells for £120 with variable production and delivery costs of £70 per unit.',
    question: 'Determine the unit break-even sales volume required to cover the marketing campaign costs.',
    options: [
      { id: 'A', text: '1,200 units' },
      { id: 'B', text: '500 units' },
      { id: 'C', text: '857 units' },
      { id: 'D', text: '1,500 units' }
    ],
    correctAnswer: 'A',
    explanation: {
      rationale: 'Unit Contribution Margin = Selling Price - Variable Cost = £120 - £70 = £50. Break-Even Volume = Fixed Marketing Overheads / Unit Contribution Margin = £60,000 / £50 = 1,200 units.',
      calculationSteps: [
        'Unit Contribution = £120 - £70 = £50',
        'Break-Even Units = £60,000 / £50 = 1,200 units'
      ],
      distractorAnalysis: {
        'B': 'Divides £60,000 by total price £120 (500 units), which fails to account for variable costs.',
        'C': 'Divides £60,000 by variable cost £70 (857 units).',
        'D': 'Adds variable and fixed costs incorrectly before dividing.'
      },
      syllabusReference: 'CIM Commercial Intelligence Specification LO 1.1 (Cost/Volume/Profit & Break-even analysis)'
    }
  },
  {
    id: 5,
    loId: 'LO1',
    criterionId: '1.2',
    commandVerb: 'Analyse',
    difficulty: 'advanced',
    scenario: 'A luxury cosmetics brand holds a 12% Market Share (SOM) in the premium skincare sector. Over the past 18 months, the brand has maintained an aggressive Share of Voice (SOV) of 22% across premium beauty publications and influencer channels.',
    question: 'According to empirical marketing performance principles (such as Excess Share of Voice - ESOV), what outcome should the marketing director forecast?',
    options: [
      { id: 'A', text: 'Market share is likely to expand over subsequent quarters due to positive ESOV (+10%).' },
      { id: 'B', text: 'Marketing expenditure is inefficient because SOV exceeds current market share by 10%.' },
      { id: 'C', text: 'Customer attrition rate will immediately double due to ad fatigue.' },
      { id: 'D', text: 'Product gross margins will contract by exactly 10%.' }
    ],
    correctAnswer: 'A',
    explanation: {
      rationale: 'When Share of Voice exceeds Share of Market (ESOV > 0), brands generate positive mental availability and salience, which drives long-term market share growth. An ESOV of +10% is a primary driver of category growth and brand strength.',
      distractorAnalysis: {
        'B': 'Misinterprets proactive growth investment as structural inefficiency.',
        'C': 'Ad fatigue is not an automatic outcome of positive ESOV in brand building.',
        'D': 'Gross margins depend on pricing and COGS, not direct SOV differentials.'
      },
      syllabusReference: 'CIM Commercial Intelligence Specification LO 1.2 (Share of Voice, Market Share, Year-on-year trends)'
    }
  },
  {
    id: 6,
    loId: 'LO1',
    criterionId: '1.2',
    commandVerb: 'Explain',
    difficulty: 'intermediate',
    scenario: 'During an annual commercial review, Product Line A recorded a 15% YoY increase in unit sales, but the gross marketing contribution declined by 8%.',
    question: 'Which of the following factors provides the most plausible commercial explanation for this performance divergence?',
    options: [
      { id: 'A', text: 'Heavy promotional price discounting and elevated paid acquisition costs eroded unit margins.' },
      { id: 'B', text: 'Customer lifetime value increased across all buyer cohorts.' },
      { id: 'C', text: 'Fixed production overheads were reclassified as non-operational expenses.' },
      { id: 'D', text: 'The brand achieved organic viral reach without paid ad spend.' }
    ],
    correctAnswer: 'A',
    explanation: {
      rationale: 'When volume grows while contribution dollars shrink, it indicates that price reductions (discounting) or inflated per-unit acquisition costs (higher CAC) outpaced the volume gain, reducing overall gross contribution.',
      distractorAnalysis: {
        'B': 'An increase in CLV would generally expand contribution over time.',
        'C': 'Reclassification of overheads would not reduce marketing contribution.',
        'D': 'Organic reach would lower CAC and increase contribution.'
      },
      syllabusReference: 'CIM Commercial Intelligence Specification LO 1.2 (Product portfolio performance & Marketing contribution)'
    }
  },
  {
    id: 7,
    loId: 'LO1',
    criterionId: '1.3',
    commandVerb: 'Interpret',
    difficulty: 'advanced',
    scenario: 'A fintech firm ran a bi-variant correlation analysis comparing weekly content marketing spend against organic conversion volume over 52 weeks, yielding a Pearson correlation coefficient (r) of +0.82 with p < 0.01.',
    question: 'How should the commercial intelligence manager interpret this data when advising on next quarter budget allocations?',
    options: [
      { id: 'A', text: 'There is a strong, statistically significant positive relationship between content spend and conversion volume.' },
      { id: 'B', text: 'Content marketing spend is proven to be the sole direct cause of 82% of all organic revenue.' },
      { id: 'C', text: 'Increasing content spend will automatically guarantee an 82% increase in customer lifetime value.' },
      { id: 'D', text: 'The relationship is random because r must exceed 1.0 to demonstrate significance.' }
    ],
    correctAnswer: 'A',
    explanation: {
      rationale: 'An r-value of +0.82 (where r ranges between -1.0 and +1.0) indicates a strong positive linear correlation, and p < 0.01 indicates high statistical significance. Correlation indicates relationship, not exclusive unilateral causation.',
      distractorAnalysis: {
        'B': 'Confuses correlation with sole definitive causation.',
        'C': 'Misinterprets correlation coefficient r as a percentage gain in CLV.',
        'D': 'The Pearson correlation coefficient is bounded strictly between -1.0 and +1.0.'
      },
      syllabusReference: 'CIM Commercial Intelligence Specification LO 1.3 (Correlation of bi-variant marketing data)'
    }
  },
  {
    id: 8,
    loId: 'LO1',
    criterionId: '1.3',
    commandVerb: 'Assess',
    difficulty: 'advanced',
    scenario: 'A retail brand runs an A/B test on checkout page checkout CTAs. Variant A (control) converted at 3.2% across 10,000 visitors. Variant B (test) converted at 3.8% across 10,000 visitors with a 95% confidence level (p = 0.02).',
    question: 'Assess the commercial validity of rolling out Variant B across the entire digital storefront.',
    options: [
      { id: 'A', text: 'Variant B delivered a statistically significant 18.75% relative lift in conversion rate, justifying full deployment.' },
      { id: 'B', text: 'The 0.6% absolute gain is too small to be meaningful regardless of sample size.' },
      { id: 'C', text: 'The test is invalid because A/B testing requires a minimum of 100,000 visitors per branch.' },
      { id: 'D', text: 'The result proves Variant B will permanently eradicate shopping cart abandonment.' }
    ],
    correctAnswer: 'A',
    explanation: {
      rationale: 'Relative conversion lift = (3.8% - 3.2%) / 3.2% = 18.75%. With p = 0.02 (< 0.05) and 10,000 samples per branch, the result is statistically robust and provides strong commercial justification for deployment.',
      distractorAnalysis: {
        'B': 'An absolute gain of 0.6% on a 3.2% base represents a substantial 18.75% revenue uplift at scale.',
        'C': 'Sample sizes depend on statistical power and baseline rate; 10,000 per branch is sufficient here.',
        'D': 'Hyperbolic claim; A/B tests do not eliminate cart abandonment entirely.'
      },
      syllabusReference: 'CIM Commercial Intelligence Specification LO 1.3 (Testing methodologies: A/B testing & Multi-variant testing)'
    }
  },

  // --- LO2: Resource Management (5Ms, MarTech, Resource Audit) (Questions 9 to 25) ---
  {
    id: 9,
    loId: 'LO2',
    criterionId: '2.1',
    commandVerb: 'Analyse',
    difficulty: 'intermediate',
    scenario: 'An organisation is conducting a resource audit using the classic 5Ms framework (Men, Money, Materials, Minutes, Measurements) to evaluate a proposed product expansion.',
    question: 'Which of the following pairings correctly aligns the 5Ms element with its practical marketing operational asset?',
    options: [
      { id: 'A', text: 'Minutes -> Time-to-market speed and project delivery schedules' },
      { id: 'B', text: 'Materials -> Financial capital reserves and venture funding' },
      { id: 'C', text: 'Measurements -> Physical promotional point-of-sale display stands' },
      { id: 'D', text: 'Men -> Automated algorithmic bidding scripts in Google Ads' }
    ],
    correctAnswer: 'A',
    explanation: {
      rationale: 'In the 5Ms framework: Men = Human capital & skills; Money = Budget & financial resources; Materials = Physical assets, raw inputs, creative collateral; Minutes = Time, scheduling & deadlines; Measurements = KPIs, metrics & tracking mechanisms.',
      distractorAnalysis: {
        'B': 'Money represents financial capital, whereas Materials represents physical/digital assets.',
        'C': 'Measurements refers to metrics, KPIs, and tracking, not physical stands.',
        'D': 'Men refers to human resources, whereas automated scripts fall under technology/materials.'
      },
      syllabusReference: 'CIM Commercial Intelligence Specification LO 2.1 (5 Ms – men, money, materials, minutes, measurements)'
    }
  },
  {
    id: 10,
    loId: 'LO2',
    criterionId: '2.1',
    commandVerb: 'Appraise',
    difficulty: 'advanced',
    scenario: 'A B2B enterprise operates 14 disparate marketing SaaS platforms across CRM, email automation, event management, and web analytics. However, data silos prevent unified attribution and lead scoring.',
    question: 'Which MarTech governance action should the commercial director prioritize to optimize resource efficiency?',
    options: [
      { id: 'A', text: 'Conduct a MarTech stack rationalization and implement a Customer Data Platform (CDP) for single-view integration.' },
      { id: 'B', text: 'Purchase additional standalone point solutions for each regional sales territory.' },
      { id: 'C', text: 'Cease all digital tracking and rely exclusively on quarterly sales reps questionnaires.' },
      { id: 'D', text: 'Double the spend on individual SaaS licences without evaluating integration APIs.' }
    ],
    correctAnswer: 'A',
    explanation: {
      rationale: 'MarTech rationalization eliminates redundant tools, cuts licensing overheads, and integrating a unified data platform (CDP) creates a single customer view, enabling accurate attribution and resource deployment.',
      distractorAnalysis: {
        'B': 'Purchasing more point solutions worsens data fragmentation and costs.',
        'C': 'Eliminating digital tracking destroys commercial intelligence capability.',
        'D': 'Doubling spend without integration increases waste without solving data silos.'
      },
      syllabusReference: 'CIM Commercial Intelligence Specification LO 2.1 (MarTech & Meaningful patterns and trends in data)'
    }
  },
  {
    id: 11,
    loId: 'LO2',
    criterionId: '2.1',
    commandVerb: 'Analyse',
    isNumerical: true,
    difficulty: 'intermediate',
    scenario: 'A digital telecom provider surveys 1,000 customers on their likelihood to recommend the brand (0-10 scale). The survey results show: 600 Promoters (scores 9-10), 250 Passives (scores 7-8), and 150 Detractors (scores 0-6).',
    question: 'Determine the Net Promoter Score (NPS) for the provider.',
    options: [
      { id: 'A', text: '+45' },
      { id: 'B', text: '+60' },
      { id: 'C', text: '+35' },
      { id: 'D', text: '+75' }
    ],
    correctAnswer: 'A',
    explanation: {
      rationale: 'NPS = % Promoters - % Detractors. % Promoters = 600 / 1,000 = 60%. % Detractors = 150 / 1,000 = 15%. NPS = 60% - 15% = +45. (Passives are excluded from the net calculation).',
      calculationSteps: [
        '% Promoters = (600 / 1000) * 100 = 60%',
        '% Detractors = (150 / 1000) * 100 = 15%',
        'NPS = 60 - 15 = +45'
      ],
      distractorAnalysis: {
        'B': 'Only looks at Promoters (60%) without subtracting Detractors.',
        'C': 'Subtracts Passives (25%) from Promoters instead of Detractors (60 - 25 = 35).',
        'D': 'Adds Promoters and Detractors incorrectly.'
      },
      syllabusReference: 'CIM Commercial Intelligence Specification LO 2.1 (Key metrics - LTV, CAC, NPS, ROI)'
    }
  },
  {
    id: 12,
    loId: 'LO2',
    criterionId: '2.2',
    commandVerb: 'Assess',
    difficulty: 'advanced',
    scenario: 'In an internal resource audit, a marketing department discovers that 65% of team hours ("Minutes") are consumed by manual reporting and ad-hoc presentation formatting, leaving insufficient capacity for campaign optimization.',
    question: 'What management recommendation best demonstrates resource effectiveness and efficiency?',
    options: [
      { id: 'A', text: 'Automate executive dashboards via BI integration to liberate strategic capacity for core optimization.' },
      { id: 'B', text: 'Hire 10 additional junior analysts to continue manual presentation formatting.' },
      { id: 'C', text: 'Cancel all commercial performance reviews to eliminate reporting requirements.' },
      { id: 'D', text: 'Outsource all strategic marketing planning to an external third-party agency.' }
    ],
    correctAnswer: 'A',
    explanation: {
      rationale: 'Efficiency focuses on doing things right (reducing manual waste via automation), while effectiveness focuses on doing the right things (redeploying skilled talent toward high-ROMI campaign optimization).',
      distractorAnalysis: {
        'B': 'Adding headcount to perpetuate low-value manual tasks inflates overhead without solving root inefficiency.',
        'C': 'Cancelling performance reviews undermines governance and accountability.',
        'D': 'Outsourcing strategy does not fix the internal workflow bottleneck.'
      },
      syllabusReference: 'CIM Commercial Intelligence Specification LO 2.2 (Resource audit – effectiveness and efficiency)'
    }
  },

  // --- LO3: Budgeting, Forecasting & Prioritisation (Questions 13 to 30) ---
  {
    id: 13,
    loId: 'LO3',
    criterionId: '3.1',
    commandVerb: 'Critically Evaluate',
    difficulty: 'advanced',
    scenario: 'A legacy consumer goods company has historically built its marketing budget by adding 5% to the previous year total spend across each division regardless of market changes.',
    question: 'Which budgeting approach should the marketing director propose to break institutional inertia and force justification of all marketing expenditures against strategic objectives?',
    options: [
      { id: 'A', text: 'Zero-Based Budgeting (ZBB)' },
      { id: 'B', text: 'Incremental Budgeting' },
      { id: 'C', text: 'Historical Percentage-of-Sales Budgeting' },
      { id: 'D', text: 'Arbitrary Allocation' }
    ],
    correctAnswer: 'A',
    explanation: {
      rationale: 'Zero-Based Budgeting (ZBB) requires every program and activity to be justified from scratch (zero base) for each new budget cycle based on expected commercial returns and alignment with objectives, eliminating legacy waste.',
      distractorAnalysis: {
        'B': 'Incremental budgeting is the exact legacy method being criticized (adding a percentage to previous baseline).',
        'C': 'Percentage-of-sales ties spending to past or projected turnover rather than objective-driven needs.',
        'D': 'Arbitrary allocation lacks strategic or commercial rigor.'
      },
      syllabusReference: 'CIM Commercial Intelligence Specification LO 3.1 (Budgeting methods: Zero-based, Activity based, Flexible, Incremental)'
    }
  },
  {
    id: 14,
    loId: 'LO3',
    criterionId: '3.1',
    commandVerb: 'Explain',
    difficulty: 'intermediate',
    scenario: 'An organisation implements an Activity-Based Budgeting (ABB) method for its global events and field marketing program.',
    question: 'What is the primary operational characteristic of Activity-Based Budgeting in marketing?',
    options: [
      { id: 'A', text: 'Budget allocations are determined by identifying the specific cost drivers and activities needed to generate required commercial outputs.' },
      { id: 'B', text: 'Each department head is given a fixed sum with no obligation to track task breakdown.' },
      { id: 'C', text: 'The budget automatically flexes based solely on prevailing bank interest rates.' },
      { id: 'D', text: 'Spend is calculated strictly by matching the competitor primary ad expenditure.' }
    ],
    correctAnswer: 'A',
    explanation: {
      rationale: 'Activity-Based Budgeting works backward from desired outputs by establishing the specific activities required (e.g. number of webinars, booth footprints, content assets) and costing each activity based on its operational resource consumption.',
      distractorAnalysis: {
        'B': 'Describes lump-sum arbitrary budgeting.',
        'C': 'Financial interest rates do not define marketing activity costs.',
        'D': 'Describes competitor parity budgeting, not activity-based.'
      },
      syllabusReference: 'CIM Commercial Intelligence Specification LO 3.1 (Budgeting methods - Activity based, Flexible)'
    }
  },
  {
    id: 15,
    loId: 'LO3',
    criterionId: '3.2',
    commandVerb: 'Recommend',
    difficulty: 'advanced',
    scenario: 'A quarterly variance report reveals the following figures for the paid search acquisition campaign:\n• Budgeted Spend: £100,000 | Actual Spend: £115,000\n• Budgeted Conversions: 2,000 | Actual Conversions: 2,800\n• Target CAC: £50 | Actual CAC: £41.07',
    question: 'How should the commercial marketing analyst interpret and explain this budget variance to the CFO?',
    options: [
      { id: 'A', text: 'Spend had an adverse cost variance of £15k, but delivered a highly favorable volume and efficiency variance, lowering CAC by 17.8% and exceeding conversion targets by 40%.' },
      { id: 'B', text: 'The campaign failed because any spend exceeding the original budget represents gross financial incompetence.' },
      { id: 'C', text: 'The £15k excess spend should be deducted from next quarter production budget as a penalty.' },
      { id: 'D', text: 'Conversions increased only because paid search ad networks suffered a technical glitch.' }
    ],
    correctAnswer: 'A',
    explanation: {
      rationale: 'While actual expenditure exceeded budget by £15,000 (an adverse spend variance), unit acquisition efficiency improved dramatically (CAC dropped from £50 to £41.07) and generated 800 extra customers (+40%), representing a strong commercial outcome under flexible budget principles.',
      distractorAnalysis: {
        'B': 'Rigid, non-commercial view that ignores massive upside in volume and efficiency.',
        'C': 'Punitive response contrary to commercial growth and value creation.',
        'D': 'Baseless conjecture that ignores performance data.'
      },
      syllabusReference: 'CIM Commercial Intelligence Specification LO 3.2 (Manage budget through variance analysis)'
    }
  },
  {
    id: 16,
    loId: 'LO3',
    criterionId: '3.2',
    commandVerb: 'Recommend',
    difficulty: 'advanced',
    scenario: 'A consumer brand exhibits high seasonal sales fluctuations across a 5-year period. The marketing director wants to forecast monthly demand while smoothing out erratic short-term anomalies.',
    question: 'Which forecasting technique is most suitable for tracking underlying trend patterns in historical time-series data?',
    options: [
      { id: 'A', text: 'Moving Averages and Centred Seasonal Trend Analysis' },
      { id: 'B', text: 'Delphi Method Intuitive Consensus' },
      { id: 'C', text: 'Zero-Sum Game Theory' },
      { id: 'D', text: 'Single-Point Anecdotal Extrapolation' }
    ],
    correctAnswer: 'A',
    explanation: {
      rationale: 'Time series analysis utilizing moving averages and seasonal decomposition isolates seasonal indices and cyclical noise, revealing the authentic underlying trajectory for commercial planning.',
      distractorAnalysis: {
        'B': 'Delphi is a qualitative expert-opinion tool, not a quantitative time-series smoothing model.',
        'C': 'Game theory analyzes competitor payoffs, not time-series sales forecasting.',
        'D': 'Anecdotal extrapolation is subjective and lacks mathematical validity.'
      },
      syllabusReference: 'CIM Commercial Intelligence Specification LO 3.2 (Predictive modelling: Time series analysis, moving averages)'
    }
  },
  {
    id: 17,
    loId: 'LO3',
    criterionId: '3.3',
    commandVerb: 'Justify',
    difficulty: 'advanced',
    scenario: 'A B2B SaaS company evaluates multi-touch marketing attribution models for a 9-month buying cycle involving whitepapers, webinars, LinkedIn ads, organic search, and sales demos.',
    question: 'Why is a "First-Touch" or "Last-Touch" single-interaction attribution model commercially misleading for this organisation?',
    options: [
      { id: 'A', text: 'Single-touch models over-credit either initial awareness or final closing actions, ignoring the vital mid-funnel nurturing touchpoints that prevent pipeline attrition.' },
      { id: 'B', text: 'Single-touch models are mathematically impossible to compute in digital spreadsheets.' },
      { id: 'C', text: 'First-touch attribution is only permitted under B2C retail accounting standards.' },
      { id: 'D', text: 'Single-touch models always underestimate overall server bandwidth consumption.' }
    ],
    correctAnswer: 'A',
    explanation: {
      rationale: 'In complex multi-stakeholder B2B journeys, single-touch attribution creates severe budget misallocation by unfairly defunding mid-funnel channels (webinars, case studies) that nurture leads between discovery and signing.',
      distractorAnalysis: {
        'B': 'Single-touch models are trivial to calculate, which is why they are often overused.',
        'C': 'There is no accounting regulation prohibiting attribution models.',
        'D': 'Attribution models relate to commercial revenue allocation, not server bandwidth.'
      },
      syllabusReference: 'CIM Commercial Intelligence Specification LO 3.3 (Apply marketing attribution techniques & Prioritising spend across channels)'
    }
  },
  {
    id: 18,
    loId: 'LO3',
    criterionId: '3.3',
    commandVerb: 'Justify',
    difficulty: 'intermediate',
    scenario: 'A marketing lead submits a formal Business Case to the executive board requesting £250,000 for an automated CRM migration.',
    question: 'Which element is essential to include in the Business Case to satisfy commercial governance and accountability requirements?',
    options: [
      { id: 'A', text: 'A detailed financial analysis with projected ROMI, risk assessment, Critical Success Factors (CSFs), and a milestone Gantt chart' },
      { id: 'B', text: 'A collection of aesthetic stock photography showcasing future software icons' },
      { id: 'C', text: 'A signed non-disclosure agreement with competing software vendors' },
      { id: 'D', text: 'An unconditional guarantee that software will never experience bugs' }
    ],
    correctAnswer: 'A',
    explanation: {
      rationale: 'A rigorous Level 6 business case must link strategy to financial analysis (ROMI/NPV), risk and sensitivity analysis, stakeholder requirements, CSFs, and clear milestone governance via Gantt charts with designated ownership.',
      distractorAnalysis: {
        'B': 'Cosmetic visual styling does not substantiate a commercial business case.',
        'C': 'Vendor NDAs are administrative procurement items, not business case justifications.',
        'D': 'Unconditional guarantees are unrealistic and ungrounded.'
      },
      syllabusReference: 'CIM Commercial Intelligence Specification LO 3.3 (Business case – Support of strategy, risks, financial analysis, CSFs, Gantt chart)'
    }
  },
  {
    id: 19,
    loId: 'LO1',
    criterionId: '1.1',
    commandVerb: 'Determine',
    isNumerical: true,
    difficulty: 'intermediate',
    scenario: 'During a month-long digital lead generation campaign, total spend was £12,000. The campaign produced 600 marketing-qualified leads (MQLs). Out of these, 90 converted into paying clients.',
    question: 'Determine the Cost Per Lead (CPL) and the Lead-to-Customer conversion rate.',
    options: [
      { id: 'A', text: 'Cost Per Lead = £20.00; Conversion Rate = 15.0%' },
      { id: 'B', text: 'Cost Per Lead = £15.00; Conversion Rate = 20.0%' },
      { id: 'C', text: 'Cost Per Lead = £20.00; Conversion Rate = 7.5%' },
      { id: 'D', text: 'Cost Per Lead = £133.33; Conversion Rate = 15.0%' }
    ],
    correctAnswer: 'A',
    explanation: {
      rationale: 'Cost Per Lead (CPL) = Total Spend / Number of Leads = £12,000 / 600 = £20.00. Lead Conversion Rate = (Paying Customers / Total Leads) × 100% = (90 / 600) × 100% = 15.0%.',
      calculationSteps: [
        'CPL = £12,000 / 600 = £20.00',
        'Lead-to-Customer Rate = (90 / 600) * 100 = 15.0%'
      ],
      distractorAnalysis: {
        'B': 'Swaps the two figures incorrectly.',
        'C': 'Halves the conversion rate calculation incorrectly.',
        'D': 'Calculates CAC (£12,000 / 90 = £133.33) rather than Cost Per Lead.'
      },
      syllabusReference: 'CIM Commercial Intelligence Specification LO 1.1 (Cost of a lead & Conversion rate)'
    }
  },
  {
    id: 20,
    loId: 'LO1',
    criterionId: '1.1',
    commandVerb: 'Determine',
    isNumerical: true,
    difficulty: 'intermediate',
    scenario: 'A subscription fitness app began the year with 10,000 active subscribers. Over the course of the year, 1,200 subscribers cancelled their membership, while 2,500 new subscribers were acquired.',
    question: 'Determine the annual Customer Attrition (Churn) Rate.',
    options: [
      { id: 'A', text: '12.0%' },
      { id: 'B', text: '25.0%' },
      { id: 'C', text: '13.0%' },
      { id: 'D', text: '8.8%' }
    ],
    correctAnswer: 'A',
    explanation: {
      rationale: 'Customer Attrition Rate = (Number of Lost Customers / Customer Base at Start of Period) × 100% = (1,200 / 10,000) × 100% = 12.0%. New acquisitions are excluded from the churn calculation.',
      calculationSteps: [
        'Churn Rate = (1,200 lost / 10,000 start) * 100 = 12.0%'
      ],
      distractorAnalysis: {
        'B': 'Calculates the acquisition rate (2,500 / 10,000 = 25%) rather than attrition.',
        'C': 'Calculates net customer growth percentage (2,500 - 1,200 = 1,300 / 10,000 = 13%).',
        'D': 'Divides lost customers by end-of-year total base (1,200 / 11,300 = 8.8%).'
      },
      syllabusReference: 'CIM Commercial Intelligence Specification LO 1.1 (Customer attrition rate)'
    }
  }
];

// Helper to get 45 questions or generate adaptive mock sets
export function getCommercialIntelligenceExamQuestions(): ExamQuestion[] {
  // If we have 20 pre-authored, let's auto-pad with syllabus-accurate generated scenarios to deliver exactly 45 questions!
  const base = [...COMMERCIAL_INTELLIGENCE_EXAM_QUESTIONS];
  
  // Ensure we reach 45 questions by procedurally varying LOs according to official CIM distribution:
  // LO1 (Metrics): ~18 questions (40%)
  // LO2 (Resource Management): ~13 questions (30%)
  // LO3 (Budgeting & Forecasting): ~14 questions (30%)
  
  const additionalQuestions: ExamQuestion[] = [
    {
      id: 21,
      loId: 'LO1',
      criterionId: '1.2',
      commandVerb: 'Analyse',
      difficulty: 'intermediate',
      scenario: 'A B2B brand observes that while its website traffic rose by 45% YoY through top-of-funnel blog posts, the sales pipeline value remained flat.',
      question: 'Which web analytics diagnosis is most likely explaining this performance gap?',
      options: [
        { id: 'A', text: 'The acquired organic traffic consists of low-intent informational seekers rather than commercial decision-makers.' },
        { id: 'B', text: 'The website SSL encryption protocol is causing form submissions to drop.' },
        { id: 'C', text: 'Customer lifetime value for existing customers has declined.' },
        { id: 'D', text: 'The brand overall share of voice is too high.' }
      ],
      correctAnswer: 'A',
      explanation: {
        rationale: 'Volume of traffic without corresponding pipeline growth indicates mismatch between audience intent (informational) and commercial conversion paths.',
        distractorAnalysis: {
          'B': 'Technical conjecture without evidence.',
          'C': 'CLV relates to existing customer tenure, not top-of-funnel visitor qualification.',
          'D': 'High SOV does not depress pipeline.'
        },
        syllabusReference: 'CIM Commercial Intelligence Specification LO 1.2 (Web analytics & Customer conversion)'
      }
    },
    {
      id: 22,
      loId: 'LO2',
      criterionId: '2.1',
      commandVerb: 'Assess',
      difficulty: 'advanced',
      scenario: 'A retailer evaluates its digital channel performance and discovers Paid Search delivers CAC of £18 with LTV of £90 (5:1 LTV:CAC), while Affiliate Marketing delivers CAC of £42 with LTV of £60 (1.4:1 LTV:CAC).',
      question: 'What strategic resource reallocation is commercially recommended?',
      options: [
        { id: 'A', text: 'Reallocate capital from Affiliate to Paid Search to capitalize on superior unit economics (5:1 ratio).' },
        { id: 'B', text: 'Discontinue Paid Search to focus entirely on improving the Affiliate channel.' },
        { id: 'C', text: 'Equalize spend across both channels regardless of unit margin efficiency.' },
        { id: 'D', text: 'Triple Affiliate commissions to encourage higher volume despite low margin.' }
      ],
      correctAnswer: 'A',
      explanation: {
        rationale: 'A 5:1 LTV:CAC ratio represents highly attractive unit economics, whereas 1.4:1 provides slim margin after operational costs. Capital should flow toward high-efficiency channels.',
        distractorAnalysis: {
          'B': 'Cutting the highest performing channel defies commercial logic.',
          'C': 'Ignoring unit economics leads to suboptimal capital allocation.',
          'D': 'Increasing costs on an already marginal channel worsens profitability.'
        },
        syllabusReference: 'CIM Commercial Intelligence Specification LO 2.1 (Channel selection & Key metrics: LTV, CAC, ROI)'
      }
    },
    {
      id: 23,
      loId: 'LO3',
      criterionId: '3.1',
      commandVerb: 'Critically Evaluate',
      difficulty: 'advanced',
      scenario: 'In an uncertain economic climate with volatile raw material prices, a multinational manufacturer is setting its annual marketing budget.',
      question: 'Which budgeting structure provides the greatest capability to adapt expenditure dynamically as revenue benchmarks fluctuate?',
      options: [
        { id: 'A', text: 'Flexible Budgeting based on tiered volume thresholds' },
        { id: 'B', text: 'Fixed Annual Incremental Budgeting' },
        { id: 'C', text: 'Fixed Historical Cap Budgeting' },
        { id: 'D', text: 'Single-Window Static Commitment' }
      ],
      correctAnswer: 'A',
      explanation: {
        rationale: 'Flexible budgets adjust spending allowance dynamically in accordance with actual revenue levels or activity volume, providing resilience in volatile environments.',
        distractorAnalysis: {
          'B': 'Fixed incremental budgets cannot adjust when market conditions diverge from initial assumptions.',
          'C': 'Fixed caps constrain growth when demand surges and fail to protect margin when demand collapses.',
          'D': 'Static commitments lack commercial responsiveness.'
        },
        syllabusReference: 'CIM Commercial Intelligence Specification LO 3.1 (Budgeting methods: Flexible, Priority based)'
      }
    },
    {
      id: 24,
      loId: 'LO3',
      criterionId: '3.2',
      commandVerb: 'Determine',
      isNumerical: true,
      difficulty: 'advanced',
      scenario: 'A company calculates quarterly moving averages to forecast Q4 sales. The 4-quarter moving average trend estimate is £450,000, and the historical seasonal index for Q4 is 1.25.',
      question: 'Determine the seasonally adjusted sales forecast for Q4.',
      options: [
        { id: 'A', text: '£562,500' },
        { id: 'B', text: '£360,000' },
        { id: 'C', text: '£450,000' },
        { id: 'D', text: '£500,000' }
      ],
      correctAnswer: 'A',
      explanation: {
        rationale: 'Seasonally Adjusted Forecast = Trend Value × Seasonal Index = £450,000 × 1.25 = £562,500.',
        calculationSteps: [
          'Forecast = £450,000 * 1.25 = £562,500'
        ],
        distractorAnalysis: {
          'B': 'Divides by 1.25 instead of multiplying (£450k / 1.25 = £360k).',
          'C': 'Ignores the seasonal index multiplier entirely.',
          'D': 'Estimates an arbitrary round number.'
        },
        syllabusReference: 'CIM Commercial Intelligence Specification LO 3.2 (Time series analysis & seasonal trend forecasting)'
      }
    },
    {
      id: 25,
      loId: 'LO3',
      criterionId: '3.3',
      commandVerb: 'Analyse',
      difficulty: 'intermediate',
      scenario: 'A customer path to purchase records: Ad Impression (Social) -> Blog Read (Organic) -> Email Newsletter Click -> Direct Website Purchase (£500 order). Under a Linear Attribution model with 4 touchpoints, how much revenue credit is assigned to the Email Newsletter?',
      question: 'Determine the revenue allocation for Email Newsletter under Linear Attribution.',
      options: [
        { id: 'A', text: '£125 (25%)' },
        { id: 'B', text: '£500 (100%)' },
        { id: 'C', text: '£0 (0%)' },
        { id: 'D', text: '£250 (50%)' }
      ],
      correctAnswer: 'A',
      explanation: {
        rationale: 'Linear Attribution distributes 100% of conversion credit equally across all recorded touchpoints. With 4 touchpoints, each receives 25% of £500 = £125.',
        calculationSteps: [
          '4 touchpoints -> each touchpoint gets 1/4 = 25%',
          'Credit = £500 * 0.25 = £125'
        ],
        distractorAnalysis: {
          'B': 'This would be Last-Touch attribution.',
          'C': 'Linear model assigns equal weight to every touchpoint.',
          'D': 'This would be a custom U-shaped or position-based model.'
        },
        syllabusReference: 'CIM Commercial Intelligence Specification LO 3.3 (Apply marketing attribution techniques)'
      }
    }
  ];

  // Combine to create the full question pool
  return [...base, ...additionalQuestions];
}
